services:
    db:
        image: postgres:15
        container_name: cs_480_postgres_db
        restart: always
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        build: .
        container_name: python_backend
        restart: always
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env
        ports:
            - '4196:4196'
        volumes:
            - .:/app
        command: python app/backend/main.py

volumes:
    pg_data:
